server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: mini-rent
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5430/mini_rent_analytics}
    username: ${DATASOURCE_USER:mini_rent_analytics}
    password: ${DATASOURCE_PASSWORD:B6LLQFNjSKxt}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 150000
      max-lifetime: 300000
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: db/master.xml
    default-schema: ${LIQUIBASE_DEFAULT_SCHEMA:mini_rent_analytics}
    liquibase-schema: ${LIQUIBASE_SCHEMA:public}
  jpa:
    generate-ddl: false
    show-sql: ${SHOW_SQL:true}
    hibernate:
      ddl-auto: validate

logging:
  level:
    org.artyomhack.common.aspects: DEBUG
